---
# defaults file for gitlab-runner
gitlab_runner_mirror: 'https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner'
gitlab_runner_concurrent_runners_per_host: '{{ ansible_processor_cores }}'
gitlab_runner_check_gitlab_new_builds_interval: 0

#Register configuration
gitlab_runner_registration_enabled: 'True'
# GitLab coordinator URL
gitlab_runner_coordinator_url: 'https://gitlab.com/ci'
# GitLab registration token
gitlab_runner_registration_token: ''
# Runner description
gitlab_runner_description: '{{ ansible_hostname }}'
# Runner executor
gitlab_runner_executor: 'shell'
# Default Docker image
#gitlab_runner_docker_image: ''
# Runner tags
gitlab_runner_tags: []
